/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.Session;
import config.dbConnector;
import java.awt.Color;
import static java.awt.Color.black;
import static java.awt.Color.blue;
import static java.awt.Color.cyan;
import static java.awt.Color.gray;
import static java.awt.Color.red;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ADMIN
 */
public class productForm extends javax.swing.JFrame {

    /**
     * Creates new form adminDashboard
     */
    public productForm() {
        initComponents();
        displayData();
        
    }
    
    boolean checkadd = true;
    
    Color navcolor = new Color(0,102,102);
    Color hovercolor = new Color(153,153,255);
    
     public void displayData(){
        try{
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT v_id, v_name, v_status, v_quantity FROM tbl_vapes");
            vTable.setModel(DbUtils.resultSetToTableModel(rs));
             rs.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());
        
        }
        
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        acc_id = new javax.swing.JLabel();
        p_add1 = new javax.swing.JPanel();
        addlabel = new javax.swing.JLabel();
        print = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        clear = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        update = new javax.swing.JPanel();
        addlabel1 = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        vTable = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        vid = new javax.swing.JTextField();
        fn1 = new javax.swing.JLabel();
        vname = new javax.swing.JTextField();
        fn = new javax.swing.JLabel();
        vprice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        vstat = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        remove = new javax.swing.JButton();
        select = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        vquant = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahe/users-removebg-preview edit.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 110));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Current user:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, 20));

        acc_id.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        acc_id.setForeground(new java.awt.Color(0, 255, 255));
        acc_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_id.setText("ID");
        jPanel1.add(acc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, -1));

        p_add1.setBackground(new java.awt.Color(0, 102, 102));
        p_add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_add1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_add1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_add1MouseExited(evt);
            }
        });
        p_add1.setLayout(null);

        addlabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addlabel.setForeground(new java.awt.Color(0, 255, 255));
        addlabel.setText("  ADD");
        p_add1.add(addlabel);
        addlabel.setBounds(70, 0, 60, 30);

        jPanel1.add(p_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 200, 30));

        print.setBackground(new java.awt.Color(0, 102, 102));
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printMouseExited(evt);
            }
        });
        print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PRINT");
        print.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 68, 30));

        jPanel1.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 200, 30));

        clear.setBackground(new java.awt.Color(0, 102, 102));
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });
        clear.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CLEAR");
        clear.add(jLabel2);
        jLabel2.setBounds(70, 0, 70, 30);

        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 200, 30));

        update.setBackground(new java.awt.Color(0, 102, 102));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.setLayout(null);

        addlabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addlabel1.setForeground(new java.awt.Color(0, 255, 255));
        addlabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addlabel1.setText("UPDATE");
        update.add(addlabel1);
        addlabel1.setBounds(60, 0, 80, 30);

        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 30));

        delete.setBackground(new java.awt.Color(0, 102, 102));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        delete.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DELETE");
        delete.add(jLabel4);
        jLabel4.setBounds(60, 0, 80, 30);

        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 30));

        jPanel9.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, 380));

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(102, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 255, 255));
        jLabel18.setText("BACK");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 80, 20));

        jLabel20.setBackground(new java.awt.Color(102, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 255, 255));
        jLabel20.setText("PRODUCT FORM");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 20));

        jPanel9.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 60));

        vTable.setBackground(new java.awt.Color(255, 255, 51));
        vTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        vTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(vTable);

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 260, 360));

        jLabel19.setBackground(new java.awt.Color(102, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setText("USER FORM");
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 20));

        vid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        vid.setEnabled(false);
        vid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vidActionPerformed(evt);
            }
        });
        jPanel9.add(vid, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 230, 30));

        fn1.setBackground(new java.awt.Color(0, 204, 204));
        fn1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        fn1.setForeground(new java.awt.Color(0, 255, 255));
        fn1.setText("Vape ID:");
        jPanel9.add(fn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 100, 30));

        vname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        vname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnameActionPerformed(evt);
            }
        });
        jPanel9.add(vname, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 230, 30));

        fn.setBackground(new java.awt.Color(0, 204, 204));
        fn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        fn.setForeground(new java.awt.Color(0, 255, 255));
        fn.setText("Vape Name:");
        jPanel9.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 100, 30));

        vprice.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        vprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vpriceActionPerformed(evt);
            }
        });
        jPanel9.add(vprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 230, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 255, 255));
        jLabel11.setText("Price:");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 100, 30));

        vstat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        vstat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Out of Stock", " " }));
        jPanel9.add(vstat, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 230, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setText("User Status:");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 100, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 320, 130));

        remove.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        remove.setText("REMOVE");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        jPanel9.add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 100, -1));

        select.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        select.setText("SELECT");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        jPanel9.add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 100, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 255, 255));
        jLabel12.setText("Stock Quantity:");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 130, 30));

        vquant.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        vquant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vquantActionPerformed(evt);
            }
        });
        jPanel9.add(vquant, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 230, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahe/jamessssss.png"))); // NOI18N
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 670, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        adminDashboard ds = new adminDashboard();
        ds.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Session sess = Session.getInstance();
        acc_id.setText(""+sess.getUid());
    }//GEN-LAST:event_formWindowActivated

    private void p_add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add1MouseClicked
        if (checkadd) {

    // Check for empty fields
    if (vname.getText().isEmpty() || vprice.getText().isEmpty() || vquant.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "All fields are Required!");
    } else {

        // Validate numeric input
        try {
            Double.parseDouble(vprice.getText()); // check price is numeric
            Integer.parseInt(vquant.getText());     // check quantity is integer
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Price and Quantity must be valid numbers!");
            return;
        }

        try {
            dbConnector dbc = new dbConnector();

            // Insert vape record including stock quantity
            String insertQuery = "INSERT INTO tbl_vapes (v_name, v_price, v_status, v_image, v_quantity) VALUES (?, ?, ?, '', ?)";
            PreparedStatement pst = dbc.connect.prepareStatement(insertQuery);
            pst.setString(1, vname.getText());
            pst.setString(2, vprice.getText());
            pst.setString(3, vstat.getSelectedItem().toString());
            pst.setInt(4, Integer.parseInt(vquant.getText()));
            pst.executeUpdate();

            // Log the insert action
            Session sess = Session.getInstance();
            int currentUserId = sess.getUid();

            if (currentUserId > 0) {
                String logAction = "Added Vape: " + vname.getText();
                String logQuery = "INSERT INTO tbl_logs (u_id, action, date) VALUES (?, ?, ?)";
                PreparedStatement logPst = dbc.connect.prepareStatement(logQuery);
                logPst.setInt(1, currentUserId);
                logPst.setString(2, logAction);
                logPst.setTimestamp(3, Timestamp.valueOf(LocalDateTime.now()));
                logPst.executeUpdate();
                logPst.close();
            }

            JOptionPane.showMessageDialog(null, "Successfully Added!");
            displayData();

            // Reset form
            checkadd = true;
            addlabel.setForeground(cyan);
            vid.setText("");
            vname.setText("");
            vprice.setText("");
            vquant.setText(""); // reset quantity
            vstat.setSelectedIndex(0);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

} else {
    JOptionPane.showMessageDialog(null, "Clear the Field First!");
}


           
        
    }//GEN-LAST:event_p_add1MouseClicked

    private void p_add1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add1MouseEntered
        p_add1.setBackground(hovercolor);
    }//GEN-LAST:event_p_add1MouseEntered

    private void p_add1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add1MouseExited
        p_add1.setBackground(navcolor);    }//GEN-LAST:event_p_add1MouseExited

    private void printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseEntered
        print.setBackground(hovercolor);
    }//GEN-LAST:event_printMouseEntered

    private void printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseExited
        print.setBackground(navcolor); 
    }//GEN-LAST:event_printMouseExited

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
         
    }//GEN-LAST:event_printMouseClicked

    private void vidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vidActionPerformed

    private void vnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vnameActionPerformed

    private void vpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vpriceActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
              
    }//GEN-LAST:event_removeActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        
    }//GEN-LAST:event_selectActionPerformed

    private void vTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vTableMouseClicked
       int rowIndex = vTable.getSelectedRow();
        
        if(rowIndex < 0){
           JOptionPane.showMessageDialog(null,"Please select an Item!");
        }else{
          
          try{
          dbConnector dbc = new dbConnector();
          TableModel tbl = vTable.getModel();
          ResultSet rs = dbc.getData("SELECT * FROM tbl_vapes WHERE v_id = '"+tbl.getValueAt(rowIndex, 0)+"'");
          if(rs.next()){
          
          vid.setText(""+rs.getInt("v_id"));
          vname.setText(""+rs.getString("v_name"));
          vprice.setText(""+rs.getString("v_price"));
          vstat.setSelectedItem(""+rs.getString("v_status"));
          vquant.setText(""+rs.getInt("v_quantity"));
          p_add1.setEnabled(false);
          addlabel.setForeground(blue);
          checkadd = false;
          
          
          } 
          }catch(SQLException ex){
              System.out.println(""+ex);
          }
          
        }  
    }//GEN-LAST:event_vTableMouseClicked

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        checkadd = true;
        addlabel.setForeground(cyan);
        vid.setText("");
        vname.setText("");
        vprice.setText("");
        vstat.setSelectedIndex(0);
        vquant.setText("");
        
    }//GEN-LAST:event_clearMouseClicked

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        clear.setBackground(hovercolor);
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        clear.setBackground(navcolor);
    }//GEN-LAST:event_clearMouseExited

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        if (vid.getText().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Please select a vape first!");
} else {
    if (vname.getText().isEmpty() || vprice.getText().isEmpty() || vquant.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "All fields are Required!");
    } else {
        // Validate price and quantity are numbers
        try {
            Double.parseDouble(vprice.getText()); // Validate price
            Integer.parseInt(vquant.getText());   // Validate quantity
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Price and Quantity must be valid numbers!");
            return;
        }

        try {
            dbConnector dbc = new dbConnector();

            // Update the vape record including quantity
            String updateQuery = "UPDATE tbl_vapes SET v_name = ?, v_price = ?, v_status = ?, v_quantity = ? WHERE v_id = ?";
            PreparedStatement pst = dbc.connect.prepareStatement(updateQuery);
            pst.setString(1, vname.getText());
            pst.setString(2, vprice.getText());
            pst.setString(3, vstat.getSelectedItem().toString());
            pst.setInt(4, Integer.parseInt(vquant.getText()));  // stock quantity
            pst.setString(5, vid.getText());
            pst.executeUpdate();

            // Insert log entry
            Session sess = Session.getInstance();
            int currentUserId = sess.getUid();

            if (currentUserId > 0) {
                String logAction = "Updated Vape ID " + vid.getText() + ": " + vname.getText();
                String logQuery = "INSERT INTO tbl_logs (u_id, action, date) VALUES (?, ?, ?)";
                PreparedStatement logPst = dbc.connect.prepareStatement(logQuery);
                logPst.setInt(1, currentUserId);
                logPst.setString(2, logAction);
                logPst.setTimestamp(3, Timestamp.valueOf(LocalDateTime.now()));
                logPst.executeUpdate();
                logPst.close();
            }

            JOptionPane.showMessageDialog(null, "Updated Successfully!");
            displayData();

            // Reset form
            checkadd = true;
            addlabel.setForeground(cyan);
            vid.setText("");
            vname.setText("");
            vprice.setText("");
            vquant.setText("");
            vstat.setSelectedIndex(0);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }
}


    }//GEN-LAST:event_updateMouseClicked

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        update.setBackground(hovercolor);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        update.setBackground(navcolor);
    }//GEN-LAST:event_updateMouseExited

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        delete.setBackground(hovercolor);
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        delete.setBackground(navcolor);
    }//GEN-LAST:event_deleteMouseExited

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseClicked

    private void vquantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vquantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vquantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_id;
    private javax.swing.JLabel addlabel;
    private javax.swing.JLabel addlabel1;
    private javax.swing.JPanel clear;
    private javax.swing.JPanel delete;
    private javax.swing.JLabel fn;
    private javax.swing.JLabel fn1;
    public javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel p_add1;
    private javax.swing.JPanel print;
    public javax.swing.JButton remove;
    public javax.swing.JButton select;
    private javax.swing.JPanel update;
    private javax.swing.JTable vTable;
    public javax.swing.JTextField vid;
    public javax.swing.JTextField vname;
    public javax.swing.JTextField vprice;
    public javax.swing.JTextField vquant;
    public javax.swing.JComboBox<String> vstat;
    // End of variables declaration//GEN-END:variables
}
